package com.example.currencyconverter.util

// DATABASE
const val CURRENCY_DATABASE_NAME = "Currency Database"

// SPLASH SCREEN
const val ANIMATION_DURATION = 1500

// CONVERT CURRENCY SCREEN
const val DEFAULT_FROM_CURRENCY_VALUE = 1
const val DEFAULT_TO_CURRENCY_VALUE = 1
const val MAX_DAILY_VALUES = 7
const val DAYS_TO_SUBTRACT_FOR_WEEKLY_RATES = 6L
const val PERCENTAGE_OF_NON_VISIBLE_SCREEN = 0.25f
const val SCALE_FOR_DIVIDED_VALUE = 3
const val BASE_CURRENCY_LABEL_HRK = "HRK"

// CURRENCY LIST SCREEN
const val FORMAT_CURRENCY_LIST_RATES = "%.3f"

// WEEKLY RATES CHART
const val MIN_AND_MAX_VALUE_OFFSET_FOR_RATE = 0.3f
const val BORDER_WIDTH = 3.0f

const val LINE_WIDTH = 2f
const val CIRCLE_RADIUS = 4f
const val FORMAT_RATE_VALUE_IN_CHART = "%.3f"
const val VALUE_TEXT_SIZE = 10f

const val X_AXIS_GRANULARITY = 1f
const val X_AXIS_OFFSET_FOR_VALUES = 0.4f
const val X_AXIS_LABEL_TEXT_SIZE = 15f
const val X_AXIS_ANIMATION_DURATION = 2000

const val Y_AXIS_LABEL_TEXT_SIZE = 15f

// SELECT CURRENCY DIALOG
const val PERCENTAGE_LAYOUT_WIDTH = 0.8f
const val PERCENTAGE_LAYOUT_HEIGHT = 0.6f
const val RADIO_BUTTON_TEXT_SIZE = 16f