package com.example.currencyconverter.util

// DATABASE
const val CURRENCY_DATABASE_NAME = "Currency Database"

// CONVERT CURRENCY SCREEN
const val DEFAULT_FROM_CURRENCY_VALUE = 1
const val DEFAULT_TO_CURRENCY_VALUE = 1
const val MAX_DAILY_VALUES = 7
const val DAYS_TO_SUBTRACT_FOR_WEEKLY_RATES = 6L

// CURRENCY LIST SCREEN
const val FORMAT_CURRENCY_LIST_RATES = "%.3f"

// WEEKLY RATES CHART
const val MIN_AND_MAX_VALUE_OFFSET_FOR_RATE = 0.3f
const val BORDER_WIDTH = 3.0f

const val NUMBER_OF_DIGITS_TO_ROUND = 3
const val LINE_WIDTH = 2f
const val CIRCLE_RADIUS = 4f

const val X_AXIS_GRANULARITY = 1f
const val X_AXIS_OFFSET_FOR_VALUES = 0.3f